"""initial schema

Revision ID: 39b064dabb4b
Revises: 
Create Date: 2026-09-20 06:16:51.701206
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '39b064dabb4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('log_sources',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_sources'))
    )
    op.create_index(op.f('ix_log_sources_code'), 'log_sources', ['code'], unique=True)
    op.create_table('machine_models',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_models'))
    )
    op.create_index(op.f('ix_machine_models_code'), 'machine_models', ['code'], unique=True)
    op.create_table('parser_versions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('parser_class', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parser_versions')),
    sa.UniqueConstraint('code', 'version', name='uq_parser_versions_code_version')
    )
    op.create_index(op.f('ix_parser_versions_code'), 'parser_versions', ['code'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('machines',
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('machine_model_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('commissioned_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], name=op.f('fk_machines_machine_model_id_machine_models'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines'))
    )
    op.create_index(op.f('ix_machines_serial_number'), 'machines', ['serial_number'], unique=True)
    op.create_table('model_configurations',
    sa.Column('machine_model_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], name=op.f('fk_model_configurations_machine_model_id_machine_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configurations')),
    sa.UniqueConstraint('machine_model_id', 'key', name='uq_model_configurations_model_key')
    )
    op.create_index(op.f('ix_model_configurations_machine_model_id'), 'model_configurations', ['machine_model_id'], unique=False)
    op.create_table('log_files',
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_role', sa.String(length=16), nullable=False),
    sa.Column('parent_file_id', sa.String(length=36), nullable=True),
    sa.Column('original_path', sa.String(length=512), nullable=True),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('machine_model_id', sa.String(length=36), nullable=True),
    sa.Column('log_source_id', sa.String(length=36), nullable=True),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.String(length=32), nullable=True),
    sa.Column('parser_code', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('line_count', sa.BigInteger(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_finished_at', sa.DateTime(), nullable=True),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['log_files.id'], name=op.f('fk_log_files_duplicate_of_id_log_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_sources.id'], name=op.f('fk_log_files_log_source_id_log_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_log_files_machine_id_machines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], name=op.f('fk_log_files_machine_model_id_machine_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_file_id'], ['log_files.id'], name=op.f('fk_log_files_parent_file_id_log_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_files'))
    )
    op.create_index(op.f('ix_log_files_checksum_sha256'), 'log_files', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_log_files_file_role'), 'log_files', ['file_role'], unique=False)
    op.create_index(op.f('ix_log_files_log_source_id'), 'log_files', ['log_source_id'], unique=False)
    op.create_index(op.f('ix_log_files_machine_id'), 'log_files', ['machine_id'], unique=False)
    op.create_index(op.f('ix_log_files_machine_model_id'), 'log_files', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_log_files_parent_file_id'), 'log_files', ['parent_file_id'], unique=False)
    op.create_index(op.f('ix_log_files_status'), 'log_files', ['status'], unique=False)
    op.create_table('machine_components',
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('machine_model_id', sa.String(length=36), nullable=True),
    sa.Column('component_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_components_machine_id_machines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], name=op.f('fk_machine_components_machine_model_id_machine_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_components'))
    )
    op.create_index(op.f('ix_machine_components_machine_id'), 'machine_components', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_components_machine_model_id'), 'machine_components', ['machine_model_id'], unique=False)
    op.create_table('log_lines',
    sa.Column('log_file_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.BigInteger(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], name=op.f('fk_log_lines_log_file_id_log_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_lines')),
    sa.UniqueConstraint('log_file_id', 'line_number', name='uq_log_lines_file_line')
    )
    op.create_index(op.f('ix_log_lines_log_file_id'), 'log_lines', ['log_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_lines_log_file_id'), table_name='log_lines')
    op.drop_table('log_lines')
    op.drop_index(op.f('ix_machine_components_machine_model_id'), table_name='machine_components')
    op.drop_index(op.f('ix_machine_components_machine_id'), table_name='machine_components')
    op.drop_table('machine_components')
    op.drop_index(op.f('ix_log_files_status'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_parent_file_id'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_machine_model_id'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_machine_id'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_log_source_id'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_file_role'), table_name='log_files')
    op.drop_index(op.f('ix_log_files_checksum_sha256'), table_name='log_files')
    op.drop_table('log_files')
    op.drop_index(op.f('ix_model_configurations_machine_model_id'), table_name='model_configurations')
    op.drop_table('model_configurations')
    op.drop_index(op.f('ix_machines_serial_number'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parser_versions_code'), table_name='parser_versions')
    op.drop_table('parser_versions')
    op.drop_index(op.f('ix_machine_models_code'), table_name='machine_models')
    op.drop_table('machine_models')
    op.drop_index(op.f('ix_log_sources_code'), table_name='log_sources')
    op.drop_table('log_sources')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
