"""transactions and transaction_events

Revision ID: e160ec93b2c1
Revises: 39b064dabb4b
Create Date: 2026-09-20 07:20:28.062649
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e160ec93b2c1'
down_revision = '39b064dabb4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=36), nullable=True),
    sa.Column('machine_model_id', sa.String(length=36), nullable=True),
    sa.Column('model_code', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('correlation_confidence', sa.Float(), nullable=False),
    sa.Column('correlation_method', sa.String(length=128), nullable=True),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_transactions_machine_id_machines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_model_id'], ['machine_models.id'], name=op.f('fk_transactions_machine_model_id_machine_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_file_id'], ['log_files.id'], name=op.f('fk_transactions_source_file_id_log_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_machine_id'), 'transactions', ['machine_id'], unique=False)
    op.create_index(op.f('ix_transactions_machine_model_id'), 'transactions', ['machine_model_id'], unique=False)
    op.create_index(op.f('ix_transactions_model_code'), 'transactions', ['model_code'], unique=False)
    op.create_index(op.f('ix_transactions_source_file_id'), 'transactions', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('transaction_events',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_code', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_code', sa.String(length=32), nullable=True),
    sa.Column('model_code', sa.String(length=32), nullable=True),
    sa.Column('log_file_id', sa.String(length=36), nullable=True),
    sa.Column('line_number', sa.BigInteger(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], name=op.f('fk_transaction_events_log_file_id_log_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_events_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_events'))
    )
    op.create_index(op.f('ix_transaction_events_event_code'), 'transaction_events', ['event_code'], unique=False)
    op.create_index(op.f('ix_transaction_events_log_file_id'), 'transaction_events', ['log_file_id'], unique=False)
    op.create_index(op.f('ix_transaction_events_transaction_id'), 'transaction_events', ['transaction_id'], unique=False)
    op.create_index('ix_transaction_events_txn_seq', 'transaction_events', ['transaction_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_events_txn_seq', table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_transaction_id'), table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_log_file_id'), table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_event_code'), table_name='transaction_events')
    op.drop_table('transaction_events')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_file_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_model_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_machine_model_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_machine_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
